clients:
  - name: "gpt4"
    type: "openai"
    config:
      model: "gpt-4"
      apiKey: "$OPENAI_API_KEY"
      temperature: 0.7
      maxTokens: 2000
flows:
  - name: "agentic_flow"
    clientName: "gpt4" # Default client for the flow
    steps:
      - name: "somnia blockchain interaction"
        executor:
          type: "llm"
          withconfig:
            template: "Interact with the blockchain using these rpc url https://rpc.ankr.com/somnia_testnet"
            systemMessage: "Fetch any network detail from the somnia blockchain."
        maxRetryTimes: 2
      - name: "get_current_block_number"
        executor:
          type: "get_current_block_number"
          withconfig:
            template: "Fetch blockchain data like current block number from the somnia network"
            systemMessage: "Fetch current block number from the somnia blockchain."
        maxRetryTimes: 2
  - name: "agentic_flow_price"
    clientName: "gpt4" # Default client for the flow
    steps:
      - name: "get_current_gas_price"
        executor:
          type: "get_current_gas_price"
          withconfig:
            template: "Fetch blockchain data like current gas price from the somnia network"
            systemMessage: "Fetch current gas price from the somnia blockchain."
        maxRetryTimes: 2
  - name: "agentic_flow_chain_id"
    clientName: "gpt4" # Default client for the flow
    steps:
      - name: "get_chain_id"
        executor:
          type: "get_chain_id"
          withconfig:
            template: "Fetch blockchain data like chain id from the somnia network"
            systemMessage: "Fetch chain id from the somnia blockchain."
        maxRetryTimes: 2

      